config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {   registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  root to: "homes#top"
  get "/home/about" => "homes#about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :users, only: [:show, :edit, :update,:index]
  resources :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_post,only: [:edit,:destroy]

  def index
    @books = Book.all
    @book_new = Book.new
    @user = current_user
  end

  def create
    @book_new = Book.new(book_params)
    @book_new.user_id = current_user.id
    @user = current_user
    if @book_new.save
      flash[:notice] = "Book was successfully created."
      redirect_to @book_new
    else
      @books = Book.all.order(id: :asc)
      flash[:notice] = "error"
      render("books/index")
    end
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to @book
    else
      flash[:notice] = "error"
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "投稿を削除しました"
    redirect_to books_path
  end

  def correct_post
      @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to books_path
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_newbook.html.erb
<!--@book_new → book_new-->
<h2 class="mt-3">New book</h2>
<%= form_with model: book_new, local: true do |f| %>
  <% if book_new.errors.any? %>
    <%= book_new.errors.count %> error
    <% book_new.errors.full_messages.each do |msg| %>
      <ul><li><%= msg %></li></ul>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body, "Opinion" %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model: @book, local:true do |f| %>
<% if @book.errors.any? %>
    <%= @book.errors.count %> error
    <% @book.errors.full_messages.each do |msg| %>
      <ul><li><%= msg %></li></ul>
    <% end %>
  <% end %>
  
  <div class="field">
    <%= f.label :title, "Title" %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body, "Body" %>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
  <%= f.submit 'Update Book' %>
  </div>
<% end %>
<%= link_to 'Show', book_path(@book) %>
|
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <!--左側-->
    <div class="col-md-3">
      <!--User info-->
      <%= render 'users/info', user: @user %>
      <!--New book-->
      <%= render 'books/newbook', book_new: @book_new %>
    </div>
    <!--右側-->
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format:'jpg', fallback:"no_image.jpg", size:"40x40" %>
                <% end %>
              </td>
              <td><%= link_to book.title, book %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <!--左側-->
    <div class="col-md-3">
      <!--User info-->
      <%= render 'users/info', user: @user %>
      <!--New book-->
      <%= render 'books/newbook', book_new: @book_new %>
    </div>
    <!--右側-->
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
       <% if @user.id == current_user.id %>
        <tbody>
            <tr>
              <td>
                <%= link_to user_path(@user.id) do %>
                  <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format:'jpg', fallback:"no_image.jpg", size:"40x40" %>
                  <%= @user.name %>
                <% end %>
              </td>
              <td><%= link_to @book.title, @book %></td>
              <td><%= @book.body %></td>
              <td><%= link_to "Edit", edit_book_path(@book.id), class: 'btn btn-sm btn-success' %></td>
              <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "Do you really want to delete this post", class: 'btn btn-sm btn-danger' %></td>
            </tr>
       <% else %>
            <tr>
              <td>
                <%= link_to user_path(@user.id) do %>
                  <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format:'jpg', fallback:"no_image.jpg", size:"40x40" %>
                  <%= @user.name %>
                <% end %>
              </td>
              <td><%= link_to @book.title, @book %></td>
              <td><%= @book.body %></td>
            </tr>
        </tbody>
       <% end %>
      </table>
    </div>
  </div>
</div>