config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {   registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  root to: "homes#top"
  get "/home/about" => "homes#about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :users, only: [:show, :edit, :update,:index]
  resources :books
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="fas fa-bars"></span>
          </button>

          <div class="navbar-collapse collapse show" id="navbarNavDropdown" style>
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <!--コード減らす為にlink_toから<a>への変換したい-->
              <li>
                <%= link_to  user_path(current_user.id)do %>
                  <div class="fas fa-home nav-link text-light">Home</div>
                <% end %>
              </li>
              <li>
                <%= link_to users_path do %>
                  <div class="fas fa-users nav-link text-light">Users</div>
                <% end %>
              </li>
              <li>
                <a class="fas fa-book-open nav-link text-light" href="/books">Books</a>
              </li>
              <li>
                <a class="fas fa-sign-out-alt nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out">logout</a>
              </li>
            <% else %>
              <li>
                <a class="fas fa-home nav-link text-light" href="/">Home</a>
              </li>
              <li>
                <a class="fas fa-link nav-link text-light" href="/home/about">About</a>
              </li>
              <li>
                <a class="fas fa-user-plus nav-link text-light" href="/users/sign_up">sign up</a>
              </li>
              <li>
                <a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in">login</a>
              </li>
            <% end %>
            </ul>

          </div>
        </div>
      </nav>
    </header>

    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <main>
    <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>